import type { Diagnosis } from "../types";

interface Props {
  diagnosis: Diagnosis;
}

export default function AiDiagnosisPanel({ diagnosis: d }: Props) {
  return (
    <div className="panel">
      <p className="panel-title">
        AI Diagnosis Engine
        <span className={`badge ${d.confidence}`} style={{ marginLeft: "auto" }}>
          <span className="badge-dot" /> {d.confidence} confidence
        </span>
      </p>

      <div className="field-block">
        <p className="field-label">Root cause</p>
        <p style={{ fontSize: 14, margin: 0, lineHeight: 1.5 }}>{d.root_cause}</p>
      </div>

      <div className="field-block">
        <p className="field-label">Evidence cited</p>
        <div className="cli-block" style={{ maxHeight: 100 }}>{d.evidence}</div>
      </div>

      <div className="field-block">
        <p className="field-label">Recommended next command</p>
        <code style={{ fontFamily: "var(--mono)", fontSize: 12.5, color: "var(--accent)" }}>{d.next_command}</code>
      </div>

      <div className="field-block">
        <p className="field-label">Fix steps</p>
        <ol className="fix-steps">
          {d.fix_steps.map((s, i) => (
            <li key={i}>
              <code>{s}</code>
            </li>
          ))}
        </ol>
      </div>

      {d.source === "offline_fallback" && (
        <p className="empty-note" style={{ marginTop: 4 }}>
          Generated by the offline fallback engine — connect an API key for a fully reasoned diagnosis.
        </p>
      )}
    </div>
  );
}
